### ISSUE TITLE
How do I show the export buttons?

### ISSUE THREAD

**Issue by emperorjm** [weizhenye/vue-highcharts#11]
I am using the following but it is not showing the export buttons:

exporting: {
                	enabled: true,
                    buttons: {
                        contextButton: {
                            enabled: true
                        }
                    }
                },

**Comment by weizhenye** [comment]
As said in [Export module docs](http://www.highcharts.com/docs/export-module/export-module-overview):

> To enable exporting, the module needs to be included.

You need to include the exporting module:

```js
import Vue from 'vue';
import VueHighcharts from 'vue-highcharts';
import Highcharts from 'highcharts';
import loadExporting from 'highcharts/modules/exporting';

loadExporting(Highcharts);

Vue.use(VueHighcharts, { Highcharts });
```
