### ISSUE TITLE
Calling chart.drillUp() throws error

### ISSUE THREAD

**Issue by brunogaspar** [weizhenye/vue-highcharts#13]
As the title says, i'm unable to successfully call `chart.drillUp()`

Here's a Fiddle https://jsfiddle.net/mwLbw11k/563/

The browser console throws an error. It works fine without Vue, so i'm unsure where the issue might be.

Any clues?

Thanks!

**Comment by weizhenye** [comment]
In your  Fiddle you call `chart.drillUp()` before vm mounted, so it throws an error for it's undefined.

Here is an example that works fine https://jsfiddle.net/mwLbw11k/565/

**Comment by brunogaspar** [comment]
Right, makes sense, it works that way.

What i'm trying to achieve is to listen to an event that's fired from a child component and when that event is fired i would call the `drillUp()`.

Listening to the event and all works fine, but calling the `drillUp()` is always giving me this error.

https://jsfiddle.net/mwLbw11k/567/

I'm most likely missing something obvious, but no idea what :)

**Comment by weizhenye** [comment]
I tried to write this without Vue and found that if the chart is not in drilldown status, calling `drillUp()` will always throw error, that's the behavior of Highcharts. If you click one column and drilled down, then calling `drillUp()` will works.

**Comment by brunogaspar** [comment]
@weizhenye Thanks for the replies.

I've used the following:

```js
if (this.$refs.highcharts.chart.series[0].options.id !== undefined) {
    this.$refs.highcharts.chart.drillUp()
}
```

And it's working fine now.
