### ISSUE TITLE
How to bind plotOptions event with Vue component Function

### ISSUE THREAD

**Issue by moJiXiang** [weizhenye/vue-highcharts#19]
![image](https://cloud.githubusercontent.com/assets/5847011/26350401/9ea56322-3fe5-11e7-9cae-e9556e56e671.png)
I want to bind a vue component function with highchart plot, but It can't bind with function with option attribute. Can refs work?

**Comment by weizhenye** [comment]
```js
function createOptions(vm) {
  return {
    plotOptions: {
      series: {
        events: {
          click() {
            // ...
            vm.yourComponentFunction();
          },
        },
      },
    },
  },
}
```
```js
{
  data() {
    return {
      options: createOptions(this),
    };
  },
}
```

Creating `options` when you can access `vm`

**Comment by moJiXiang** [comment]
Thank you. It works. I'm stupid.
