### ISSUE TITLE
How to use highcharts themes?

### ISSUE THREAD

**Issue by sebastianmacias** [weizhenye/vue-highcharts#20]
If I want to use one of these [themes](http://jkunst.com/highcharts-themes-collection) how would I set it up using vue-highcharts?

Thanks

**Comment by weizhenye** [comment]
See document https://www.highcharts.com/docs/chart-design-and-style/themes

For example, [the simple theme](https://raw.githubusercontent.com/jbkunst/highcharts-themes-collection/gh-pages/themes/smpl.js), it's in JSON format, you should add `export default ` at the begin of this file if you want use ES Module, then use like this:

```js
import Vue from 'vue';
import VueHighcharts from 'vue-highcharts';
import Highcharts from 'highcharts';
import smplTheme from './path/to/smpl.js';

Highcharts.theme = smplTheme;
Highcharts.setOptions(Highcharts.theme);

Vue.use(VueHighcharts, { Highcharts });
```

**Comment by sebastianmacias** [comment]
Perfect, thanks! I think you should add this to the README or I could make a PR if want to.

**Comment by weizhenye** [comment]
Actually theme can be changed after initialization by calling `vm.Highcharts.setOptions(smplTheme);`, I think it's more related to Highcharts itself.
