### ISSUE TITLE
Download options does not appear 

### ISSUE THREAD

**Issue by marcoapferegrino** [weizhenye/vue-highcharts#23]
Hi, I am creating charts but I noticed download options does not appear in the chart and reading your documentation I can't find what should I do to implement this part.

**Comment by weizhenye** [comment]
Download options are provided by [exporting module](https://www.highcharts.com/docs/export-module/export-module-overview), you should import it.

```js
import Vue from 'vue';
import VueHighcharts from 'vue-highcharts';
import Highcharts from 'highcharts';
import loadExporting from 'highcharts/modules/exporting';

loadExporting(Highcharts);

Vue.use(VueHighcharts, { Highcharts });
```

**Comment by marcoapferegrino** [comment]
Great. Got it I guessed this part was not included. Thanks !
