### ISSUE TITLE
a.Highcharts.error

### ISSUE THREAD

**Issue by cotein** [weizhenye/vue-highcharts#29]
Hello everybody:
first, i sorry by my horrible english.
I am working in a project with vue-highcharts but at moment to run display this error (TypeError: a.Highcharts.error is not a function) and them nothing!

Someone happened something like this?
I hope you can help me.

Bye people and thanks.

**Comment by weizhenye** [comment]
Could you provide a minimal example to reproduce this error?

**Comment by weizhenye** [comment]
The [Highcharts.error](http://api.highcharts.com/highcharts/Highcharts.error) API is introduced in v5.0.6, I'm guessing it might be you're using a previous version. If you still get this error after checking the Highcharts verison, please provide a example to reproduce this error and fell free to reopen this issue.
