### ISSUE TITLE
How to implement Renderer.text

### ISSUE THREAD

**Issue by kevinhofmaenner** [weizhenye/vue-highcharts#30]
First, thanks for writing this great component! 

I am using a gauge plot and wanted to annotate the chart freely via the Renderer.text API (http://api.highcharts.com/highcharts/Renderer.text).

How can I get functions to immediately fire that are called as the third parameter to Highcharts.chart?

Example below:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/renderer-text-on-chart/

Thanks!

**Comment by weizhenye** [comment]
You can get the `chart` instance by refs:
```vue
<highcharts :options="options" ref="highcharts"></highcharts>
```
```js
const { chart } = this.$refs.highcharts;
chart.renderer.text(/* arguments */);
```
