### ISSUE TITLE
Conflicts with existing global highcharts instance

### ISSUE THREAD

**Issue by scaret** [weizhenye/vue-highcharts#31]
In my case, Highcharts has been included as global instance, and "import VueHighcharts from 'vue-highcharts'" throws highcharts error 16

https://www.highcharts.com/errors/16

Is it supported that vue-highcharts works with global highcharts together?

**Comment by weizhenye** [comment]
If you include Highcharts as a global variable and want vue-highcharts to use this, you should include vue-highcharts as global too.

```html
<script src="/path/to/highcharts.js"></script>
<script src="/path/to/vue-highcharts.js"></script>
```

```js
import Vue from 'vue';
Vue.use(window.VueHighcharts);
// or specify the `Highcharts` clearly
Vue.use(window.VueHighcharts, { Highcharts: window.Highcharts });
```

**Comment by scaret** [comment]
I removed the dependency from `vue-highcharts` to `highcharts`, passing the global Highcharts object and it works.

https://github.com/scaret/vue-highcharts/commit/eb0be06b30bc0fa115846e71a1084e0c820b8af4

I think the problem is that Highcharts package injects something on the global, which is not so necessary.
