### ISSUE TITLE
How to disable useUTC in global options using this component?

### ISSUE THREAD

**Issue by canfone** [weizhenye/vue-highcharts#33]
Hi,

Sorry for my ignorance but how do I disable useUTC in global options using this component?

I'm looking forward for your response. 
Thanks,

**Comment by weizhenye** [comment]
You can set global options before initialization, after that you can still access `Highcharts` object via `vm.Highcharts`.

```js
import Vue from 'vue';
import VueHighcharts from 'vue-highcharts';
import Highcharts from 'highcharts';

Highcharts.setOptions({
  global: {
    useUTC: false
  }
});

Vue.use(VueHighcharts, { Highcharts });
```
