### ISSUE TITLE
Invalid prop: type check failed for prop "options". Expected Object, got Undefined.

### ISSUE THREAD

**Issue by sayhitoarvind** [weizhenye/vue-highcharts#36]
Do you know what is the issue? Do i need any lifecycle hooks?

**Comment by weizhenye** [comment]
Just as it says, `options` should be a `Object`, but you passed in a `undefined`.

**Comment by sayhitoarvind** [comment]
I'm using highcharts for the first time. I was trying to implement your demo https://codepen.io/weizhenye/pen/rrKgbP and i keep getting the same error. Like i'm fairly new to Vue.js too so any leads would be helpful.

**Comment by weizhenye** [comment]
Please provide a example to eproduce it

**Comment by sayhitoarvind** [comment]
`
<template>

<el-card class="box-card">

<highcharts :options="options"></highcharts>


</el-card>




</template>
<style>

</style>


<script>
let options = {
  title: {
    text: 'Monthly Average Temperature',
    x: -20 //center
  },
  subtitle: {
    text: 'Source: WorldClimate.com',
    x: -20
  },
  xAxis: {
    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ]
  },
  yAxis: {
    title: {
      text: 'Temperature (°C)'
    },
    plotLines: [{
      value: 0,
      width: 1,
      color: '#808080'
    }]
  },
  tooltip: {
    valueSuffix: '°C'
  },
  legend: {
    layout: 'vertical',
    align: 'right',
    verticalAlign: 'middle',
    borderWidth: 0
  },
  series: [{
    name: 'Tokyo',
    data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
  }, {
    name: 'New York',
    data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
  }, {
    name: 'Berlin',
    data: [-0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]
  }, {
    name: 'London',
    data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
  }]
}

export default {
  name: 'Graph',
  components: { },
  data() {
          return {
            options: options
          }
}
}

`

**Comment by sayhitoarvind** [comment]
![1](https://user-images.githubusercontent.com/717765/32344459-537baa28-bfdd-11e7-960d-1fb01b0dd47a.PNG)
![options](https://user-images.githubusercontent.com/717765/32344481-64d20aba-bfdd-11e7-8bda-28ba92094b70.PNG)
![3](https://user-images.githubusercontent.com/717765/32344489-6a8b2e64-bfdd-11e7-869c-758a0cf8e628.PNG)

This is what i was trying. Thanks

**Comment by weizhenye** [comment]
Is the second picutrue and third picutrue in the same file? Try to `console.log(options);` before `return { options: options }` to see if it can be accessed here.
