### ISSUE TITLE
Error when using Highcharts styled mode

### ISSUE THREAD

**Issue by rriixx** [weizhenye/vue-highcharts#47]
If i try to use [Highcharts styled mode](https://www.highcharts.com/docs/chart-design-and-style/style-by-css) i'm getting the following error:

`[Vue warn]: Error in callback for watcher "options": "TypeError: Cannot read property '0' of undefined"`
<img width="775" alt="screen shot 2018-03-07 at 16 44 34" src="https://user-images.githubusercontent.com/7082458/37101956-03b35d5e-2227-11e8-9e88-6b2c471bfe0e.png">

I simply imported the highcharts file under `/js/` folder like this
`import Highcharts from 'highcharts/js/highstock'`

Is it currently not possible to use styled mode or how does it work?

**Comment by weizhenye** [comment]
It should be work as usual.

You can try it at https://codepen.io/weizhenye/pen/mWxZEv
1. click Settings
2. in JavaScript tab, change `https://unpkg.com/highcharts/highstock.js` to `https://unpkg.com/highcharts/js/highstock.js`
3. in CSS tab, add `https://unpkg.com/highcharts/css/highcharts.css`

This chart should be same as before.

With build process, not sure what you missed, try this:

```js
import Vue from 'vue';
import VueHighcharts from 'vue-highcharts';
import Highcharts from 'highcharts/js/highstock';

Vue.use(VueHighcharts, { Highcharts });
```

**Comment by rriixx** [comment]
got it working now.
problem was caused by `navigator.series.data` i added the data for the navigator series manually before. Also i had to delete the navigator options in my chart options object.
thx for u'r help!
