### ISSUE TITLE
How to change Highcharts object configuration locally?

### ISSUE THREAD

**Issue by DaveGitUser** [weizhenye/vue-highcharts#48]
I am wondering if there is a way to set options and stuff localy, not only globally.
I use following plugin instalation:

```
Highcharts.Pointer.prototype.reset = function () {
    return undefined;
};

Vue.use(VueHighcharts, { Highcharts });
```

Unfortunately, this means that the reset function is not working in all charts in all pages. Is there a way, how to set some config options only for certain chart?

**Comment by weizhenye** [comment]
What specific stuff do you want to implement? Modifying methods of library itself is never a good practice.

**Comment by DaveGitUser** [comment]
I want to implement chart synchronisation, as it is in following snippet:

[https://www.highcharts.com/blog/snippets/synchronisation-of-multiple-charts/](url)

But not globally, only for three certain charts.

Is it possible with VueHighcharts somehow?

**Comment by weizhenye** [comment]
The official demo will also affect the global Highcharts. It's wrong.

I rewrite it. See https://codepen.io/weizhenye/pen/NYPZMK

**Comment by DaveGitUser** [comment]
Perfect! Thanks a lot, it works!
