### ISSUE TITLE
why highstocks use this method does not take effect

### ISSUE THREAD

**Issue by wen-dong** [weizhenye/vue-highcharts#49]
import Vue from 'vue'
import vueHighcharts from 'vue-highcharts';

import Highcharts from 'highcharts';
import loadStock from 'highcharts/modules/stock';
loadStock(Highcharts);

export default () => {
    Vue.use(vueHighcharts, { Highcharts })
}

**Comment by weizhenye** [comment]
Please provide more information. What do you want to do? What's the result or error you got from above code?
