### ISSUE TITLE
Highcharts this.$refs undefined in mounted

### ISSUE THREAD

**Issue by poloma** [weizhenye/vue-highcharts#55]
I'm trying to add data once the component is mounted by accessing this.$refs.highcharts but Vue says it's undefined

```javascript
methods: {
  updateChartData () {
    const { chart } = this.$refs.highcharts
    chart.series[0].setData(this.chartData, true)
  }
},
mounted () {
  this.updateChartData()
}
```

Error in mounted hook: "TypeError: Cannot read property 'chart' of undefined"'

Any ideas? Or better way of initializing data with a calculated field.

**Comment by weizhenye** [comment]
Do you forgot to write the `ref` props?

```vue
<highcharts :options="options" ref="highcharts"></highcharts>
```

**Comment by poloma** [comment]
No, I am able to update the ref on a click but it seems the ref is just not available during the mounted hook.

**Comment by poloma** [comment]
@weizhenye Thank you that was it! My mistake.
