### ISSUE TITLE
vue-highcharts with typescript 

### ISSUE THREAD

**Issue by tonytomk** [weizhenye/vue-highcharts#59]
Hi
my project is developed using @vue/cli 3.0. and we are using typescript as the script language
does vue-highcharts support typescript because I am not able to get the typings file for the same

![image](https://user-images.githubusercontent.com/19387522/43759666-9313414c-9a3d-11e8-8690-9be218242184.png)

**Comment by weizhenye** [comment]
I'm not familiar with TypeScript, but vue-highcharts doesn't provide any methods, I think there is nothing can be provided in typings file.
