### ISSUE TITLE
推荐使用 Highcharts 官方维护的 Vue 包

### ISSUE THREAD

**Issue by zhy1stgg** [weizhenye/vue-highcharts#65]
推荐使用 Highcharts 官方维护的 Vue 包：[highcharts-vue](https://github.com/highcharts/highcharts-vue)

优势：

1. 由 Highcharts 官方维护，及时更新和 Bug 修复
2. 支持 Typescript
3. 支持图表初始化完毕的回调函数

**Comment by weizhenye** [comment]
劣势：
1. 由 Highcharts 官方维护，更新和 Bug 修复很不及时，Issue 都有 open 一年的
2. 不支持服务端渲染
3. 包大小
