### ISSUE TITLE
missingModuleFor: bullet"

### ISSUE THREAD

**Issue by Sweetyy** [weizhenye/vue-highcharts#66]
Hi !

I just updated to the last version of highcharts and vue-highcharts but still have this error :

`ue warn]: Error in mounted hook: "Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=bullet
missingModuleFor: bullet"`

Any help ?

Thx in advance ! :)

**Comment by weizhenye** [comment]
load the bullet module when init
```js
import Vue from 'vue';
import VueHighcharts from 'vue-highcharts';
import Highcharts from 'highcharts';

import loadBullet from 'highcharts/modules/bullet.js';

loadBullet(Highcharts);
Vue.use(VueHighcharts, { Highcharts });
```
