### ISSUE TITLE
highcharts Update

### ISSUE THREAD

**Issue by DasonCheng** [weizhenye/vue-highcharts#7]
当实时更新chart时，highcharts Update the series with a new set of options.[highcharts update](http://api.highcharts.com/highstock/Series.update) ，使用vue-highcharts更新options，chart会整体重新绘制，可能是我方法不对，请问怎样更新`series`中的`data`而不导致整体重新绘制

**Comment by weizhenye** [comment]
vue-highcharts 仅仅监听了整个 options，有变动时就整体重绘。部分重绘在计划中，目前还没实现。

目前如果你要实现部分重绘，可以用 `$refs` 拿到 `chart` 实例，直接调用它的 API，比如你链接的那个。

**Comment by DasonCheng** [comment]
好的，谢谢！
