### ISSUE TITLE
请问如何在外部调用组件方法，比如 point.slice()

### ISSUE THREAD

**Issue by liujinyang1994** [weizhenye/vue-highcharts#8]
谢谢

**Comment by weizhenye** [comment]
README 里有写，使用 child refs

```html
<highcharts :options="options" ref="highcharts"></highcharts>
```
```js
const chart = vm.$refs.highcharts.chart;
```

然后比如 [Point.slice](http://api.highcharts.com/highcharts/Point.slice) 给出的[例子](https://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/highcharts/members/point-slice/)，上面拿到的 chart 实例可以 `chart.series[0].data[0].slice();` 这样用。
