### ISSUE TITLE
On destroy removes chart before vue transitions finish

### ISSUE THREAD

**Issue by ErwanLent** [weizhenye/vue-highcharts#9]
If the highcharts component is in another component that has a vue transition (like a fade out), the highchart component ignores this and is deleted right away.

Visually, removing everything in the beforeDestroy event fixes it.
https://github.com/weizhenye/vue-highcharts/blob/master/dist/vue-highcharts.js#L71

I'm wondering if this will cause any unexepected errors down the line or any broken references. Is this fix safe to use?

**Comment by ErwanLent** [comment]
Example here:

https://jsfiddle.net/mwLbw11k/355/

**Comment by weizhenye** [comment]
Remove beforeDestroy may cause memory leak, you can find it with Chrome DevTools, repeat show and hide Modal several times, click Profiles -> Take Heap Snapshot -> Take Snapshot, then find Detached DOM tree.

Maybe we should find other ways to fix it.

**Comment by weizhenye** [comment]
I tried to replace `beforeDestroy` with `destroyed`, but found that `destroyed` is also triggered before `afterLeave`, and it's [intended behavior in 2.x](https://github.com/vuejs/vue/issues/4782).

**Comment by ErwanLent** [comment]
Okay, good to know. I'll play around with some possible solutions today.

**Comment by ErwanLent** [comment]
I've found a solution. chart.destroy() needs to be called for there to be no memory leak. However, if you wait a delay inside the beforeDestroy event, this.chart becomes null and you cannot call destroy() on it. Highcharts, however, saves all the charts globally in Highcharts.charts. If you store the chart id in beforeDestroy, wait a delay for a transition to finish, then call the destroy() function on the chart stored in the Highcharts.charts array, the problem is solved.

I've forked the repo and added a destroyDelay prop that gives the option of putting in a millisecond amount before the highcharts is destroyed. I've run the build process, forked the repo, and opened a pull request. Please feel free to change the prop name.

**Comment by weizhenye** [comment]
I think #10 is not a proper solution to solve it.

Suppose there is a transition with 1s and I set `destroyDelay` to 1s, someday I extend transition to 2s, then I have to change `destroyDelay` too, I think components should not coupled with its style.

In this situation, we may use [`<keep-alive>`](https://vuejs.org/v2/api/#keep-alive) to solve it.
```vue
<keep-alive>
  <modal v-if="showModal" @close="showModal = false">
    <h3 slot="header">custom header</h3>
  </modal>
</keep-alive>
```

**Comment by ErwanLent** [comment]
That solution works, thanks!
